### ISSUE TITLE
Find maintainer

### ISSUE THREAD

**Issue by ipmb** [ipmb/django-discover-jenkins#21]
We don't have anybody maintaining or using this project anymore. @camilonova would you like to take it over?

**Comment by camilonova** [comment]
Yes Peter we can take it, we just need to transfer the repo and give me access to pypi. @ipmb

**Comment by ipmb** [comment]
Can you delete or rename your fork? It's preventing me from transferring.

**Comment by ipmb** [comment]
@bkonkle it looks like you own the PyPI repo. Can you look into transferring it? I'm not sure what's necessary there.

**Comment by bkonkle** [comment]
It looks like I just need to log in to the admin interface. What PyPI
username should I transfer it to?

**Comment by camilonova** [comment]
camilonova

**Comment by camilonova** [comment]
@ipmb done, please try again

**Comment by bkonkle** [comment]
All set. Thanks!

**Comment by camilonova** [comment]
@bkonkle great. Thanks.

**Comment by ipmb** [comment]
Should be moved momentarily. Thanks @camilonova!
![options](https://cloud.githubusercontent.com/assets/319156/5845185/2a2fe620-a177-11e4-9fb3-8bcf16a60e90.png)
